import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const digest = (bytes) => createHash("sha256").update(bytes).digest("hex");
function stableJson(value) {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  return `{${Object.keys(value)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`)
    .join(",")}}`;
}
const entryDigest = (value) => digest(Buffer.from(stableJson(value)));
const sameEntry = (left, right) => stableJson(left) === stableJson(right);
function json(value, depth = 0) {
  if (Array.isArray(value)) return `[${value.map((item) => JSON.stringify(item)).join(", ")}]`;
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (!Object.keys(value).length) return "{}";
  const indent = "  ".repeat(depth);
  const output = `{\n${Object.entries(value)
    .map(([key, item]) => `${indent}  ${JSON.stringify(key)}: ${json(item, depth + 1)}`)
    .join(",\n")}\n${indent}}`;
  return output + (depth === 0 ? "\n" : "");
}
const statePath = ".agents/provider-sync.json";
const marker = "funnysoft-provider-sync";
const bridge = "<!-- Generated by provider-sync.mjs. Edit AGENTS.md. -->\n\n@AGENTS.md\n";
const policy = `<!-- ${marker}:start -->

## Shared agent instructions

Before work, read the applicable \`.agents/rules/*.md\` files and the pinned \`docs/playbook/README.md\` when present. Rule frontmatter describes scope; \`alwaysApply: true\` rules apply to every task. Read nested \`AGENTS.md\` files before editing their directories. Product facts and named deviations take priority.

Portable skills live in \`.agents/skills/<name>/SKILL.md\`. Read the relevant skill when its description matches the task. Generated provider files are adapters; edit canonical instructions, skills, reviewers and \`.agents/mcp.json\`, then run \`node scripts/provider-sync.mjs\`. Use the selected provider's native subagent tool for delegation. If a named reviewer is unavailable, pass its canonical \`.agents/reviewers/<name>.md\` instructions to a supported read-only subagent. If no subagent tool exists, return the review requirement to the coordinator.
<!-- ${marker}:end -->`;

function fail(message) {
  throw new Error(message);
}
function object(value, label) {
  if (!value || Array.isArray(value) || typeof value !== "object")
    fail(`expected object: ${label}`);
  return value;
}
function scopedBlock(text, content, prefix = "<!-- ", suffix = " -->") {
  const start = `${prefix}${marker}:start${suffix}`;
  const end = `${prefix}${marker}:end${suffix}`;
  const from = text.indexOf(start),
    to = text.indexOf(end);
  if (
    from < 0 !== to < 0 ||
    (from >= 0 &&
      (to < from ||
        text.indexOf(start, from + start.length) >= 0 ||
        text.indexOf(end, to + end.length) >= 0))
  )
    fail("malformed provider-sync markers");
  if (from >= 0) return text.slice(0, from) + content + text.slice(to + end.length);
  return text.trimEnd() + (text.trim() ? "\n\n" : "") + content + "\n";
}

// Pure planning until every source, destination and conflict has been checked.
// Existing canonical content wins. Ambiguous migrations stop before any writes.
export function syncProviders({ root = process.cwd(), check = false, preserveClaude } = {}) {
  root = path.resolve(root);
  const original = new Map(),
    writes = new Map(),
    removals = new Set(),
    modes = new Map();
  function location(name) {
    if (
      !name ||
      path.isAbsolute(name) ||
      name.split("/").some((part) => part === ".." || !part) ||
      name.includes("\\")
    )
      fail(`invalid relative path: ${name}`);
    let cursor = root;
    for (const part of ["", ...name.split("/")]) {
      cursor = path.join(cursor, part);
      const stat = fs.lstatSync(cursor, { throwIfNoEntry: false });
      if (stat?.isSymbolicLink()) fail(`symlink path: ${name}`);
    }
    return path.join(root, name);
  }
  function read(name) {
    if (!original.has(name)) {
      const file = location(name);
      const stat = fs.lstatSync(file, { throwIfNoEntry: false });
      if (stat && !stat.isFile()) fail(`expected file: ${name}`);
      original.set(name, stat ? fs.readFileSync(file) : null);
    }
    return writes.get(name) ?? original.get(name);
  }
  function write(name, bytes) {
    read(name);
    writes.set(name, Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes));
  }
  function parse(name, fallback) {
    const bytes = read(name);
    if (!bytes) return fallback;
    try {
      return object(JSON.parse(bytes.toString()), name);
    } catch {
      fail(`invalid JSON object: ${name}`);
    }
  }
  function files(directory) {
    const absolute = location(directory);
    if (!fs.existsSync(absolute)) return [];
    return fs
      .readdirSync(absolute, { withFileTypes: true })
      .sort((a, b) => a.name.localeCompare(b.name))
      .flatMap((entry) => {
        const name = `${directory}/${entry.name}`;
        location(name);
        return entry.isDirectory() ? files(name) : [name];
      });
  }
  const state = parse(statePath, { schemaVersion: 1, generated: {} });
  if (state.schemaVersion !== 1) fail("unsupported provider-sync receipt schema");
  object(state.generated, statePath);
  const preservedClaude = [...new Set(preserveClaude ?? state.preservedClaude ?? [])].sort();
  for (const name of preservedClaude) {
    if (typeof name !== "string" || !/(^|\/)CLAUDE\.md$/.test(name) || !read(name))
      fail("--preserve-claude requires an existing repository-relative CLAUDE.md file");
  }
  const generated = {};
  function adapter(name, content) {
    const current = read(name),
      bytes = Buffer.from(content);
    if (current && !current.equals(bytes) && !writes.has(name)) {
      if (state.generated[name] && digest(current) !== state.generated[name])
        fail(`edited generated file: ${name}; reconcile it with the canonical source first`);
      if (!state.generated[name])
        fail(
          `unmanaged adapter conflict: ${name}; preserve its content in the canonical source first`,
        );
    }
    write(name, bytes);
    generated[name] = digest(bytes);
  }
  adapter("scripts/provider-sync.mjs", fs.readFileSync(fileURLToPath(import.meta.url)));
  function promote(source, destination) {
    const bytes = read(source),
      current = read(destination);
    if (current && !current.equals(bytes))
      fail(`conflicting canonical file: ${destination}; reconcile ${source} first`);
    if (!current) write(destination, bytes);
    if (!current) modes.set(destination, fs.statSync(location(source)).mode & 0o777);
    removals.add(source);
  }
  for (const kind of ["rules", "skills"]) {
    for (const source of files(`.opencode/${kind}`))
      promote(source, source.replace(".opencode/", ".agents/"));
  }
  // The old OpenCode reviewer is team behavior. Strip only its native metadata.
  const oldReviewer = ".opencode/agent/adversary.md";
  const reviewer = ".agents/reviewers/adversary.md";
  if (read(oldReviewer) && !state.generated[oldReviewer]) {
    const text = read(oldReviewer).toString();
    const metadata = text.match(/^---\n([\s\S]*?)\n---\n/);
    if (
      metadata &&
      metadata[1].split("\n").some((line) => line && !/^(description|mode):/.test(line))
    )
      fail("reviewer has provider-specific metadata; author .agents/reviewers/adversary.md first");
    const body = text.replace(/^---\n[\s\S]*?\n---\n\n?/, "");
    if (read(reviewer) && read(reviewer).toString() !== body)
      fail("conflicting canonical reviewer; reconcile .opencode/agent/adversary.md first");
    if (!read(reviewer)) write(reviewer, body);
    // This known migration is allowed to replace the old native definition.
    state.generated[oldReviewer] = digest(read(oldReviewer));
  }
  const entry = (read("AGENTS.md")?.toString() ?? "# Agent instructions\n")
    .replaceAll(".opencode/rules", ".agents/rules")
    .replaceAll(".opencode/skills", ".agents/skills");
  write("AGENTS.md", scopedBlock(entry, policy));
  const excluded = new Set([
    ".git",
    ".agents",
    ".claude",
    ".grok",
    ".cursor",
    ".codex",
    ".opencode",
    "node_modules",
    "vendor",
    ".next",
    ".turbo",
    "dist",
    "build",
    "coverage",
  ]);
  const scopes = [""];
  function discover(directory = "") {
    for (const entry of fs.readdirSync(path.join(root, directory), { withFileTypes: true })) {
      if (
        entry.isSymbolicLink() ||
        excluded.has(entry.name) ||
        entry.name.startsWith(".boost-sync.")
      )
        continue;
      const name = directory ? `${directory}/${entry.name}` : entry.name;
      if (entry.isDirectory()) discover(name);
      else if (entry.name === "AGENTS.md" && directory) scopes.push(directory);
    }
  }
  discover();
  for (const scope of scopes.sort()) {
    const name = scope ? `${scope}/CLAUDE.md` : "CLAUDE.md";
    if (preservedClaude.includes(name)) continue;
    const instructions = scope ? `${scope}/AGENTS.md` : "AGENTS.md";
    const current = read(name);
    read(instructions);
    if (
      current &&
      !state.generated[name] &&
      (original.get(instructions)?.equals(current) || current.toString().trim() === "@AGENTS.md")
    )
      state.generated[name] = digest(current);
    adapter(name, bridge);
  }

  // OpenCode, Codex and Cursor discover .agents/skills. Claude and Grok need
  // real native skill files, including references and executable resources.
  const skillFiles = new Set(
    [...files(".agents/skills"), ...writes.keys()].filter((name) =>
      name.startsWith(".agents/skills/"),
    ),
  );
  for (const source of [...skillFiles].sort()) {
    const parts = source.split("/");
    const skill = `.agents/skills/${parts[2]}/SKILL.md`;
    if (!read(skill)) fail(`SKILL.md missing: ${parts[2]}`);
    for (const destination of [".claude/skills", ".grok/skills"]) {
      const name = source.replace(".agents/skills", destination);
      adapter(name, read(source));
      modes.set(name, modes.get(source) ?? fs.statSync(location(source)).mode & 0o777);
    }
  }
  if (read(reviewer)) {
    const prompt =
      "Read AGENTS.md and applicable scoped instructions, then follow .agents/reviewers/adversary.md. Review only; do not edit files, commit, push, or change issue state.\n";
    adapter(
      oldReviewer,
      `---\ndescription: Adversarial reviewer for plans, docs, and diffs.\nmode: subagent\n---\n\n${prompt}`,
    );
    for (const directory of [".claude/agents", ".cursor/agents"])
      adapter(
        `${directory}/adversary.md`,
        `---\nname: adversary\ndescription: Adversarial reviewer for plans, docs, and diffs.\n---\n\n${prompt}`,
      );
    adapter(
      ".codex/agents/adversary.toml",
      `developer_instructions = ${JSON.stringify(prompt.trim())}\n`,
    );
  }

  const opencode = parse("opencode.json", {});
  for (const key of ["agents", "permissions", "providers", "commands", "plugins"])
    if (Object.hasOwn(opencode, key))
      fail(`OpenCode V2-only field ${key}; reconcile with V1 before provider sync`);
  if (read("opencode.jsonc"))
    fail("opencode.jsonc exists; reconcile it into opencode.json before sync");
  let canonical = parse(".agents/mcp.json", null);
  if (!canonical) {
    const legacy = opencode.mcp?.servers ?? opencode.mcp ?? {};
    canonical = { servers: Object.create(null) };
    for (const [name, value] of Object.entries(object(legacy, "OpenCode MCP"))) {
      if (
        !/^[a-zA-Z0-9_-]+$/.test(name) ||
        ["__proto__", "prototype", "constructor"].includes(name)
      )
        fail("invalid MCP server name");
      object(value, `MCP server ${name}`);
      if (
        Object.keys(value).some(
          (key) => !["type", "command", "url", "enabled", "disabled"].includes(key),
        )
      )
        fail(
          `MCP server ${name} has nonportable fields; author a credential-free .agents/mcp.json first`,
        );
      canonical.servers[name] = {
        ...(value.command ? { command: value.command } : { url: value.url }),
        ...(value.enabled === false || value.disabled === true ? { enabled: false } : {}),
      };
    }
    write(".agents/mcp.json", json(canonical));
  }
  if (Object.keys(canonical).some((key) => key !== "servers"))
    fail("unsupported .agents/mcp.json field");
  const servers = object(canonical.servers, ".agents/mcp.json servers");
  const native = Object.create(null),
    open = Object.create(null);
  for (const [name, value] of Object.entries(servers).sort(([a], [b]) => a.localeCompare(b))) {
    if (!/^[a-zA-Z0-9_-]+$/.test(name) || ["__proto__", "prototype", "constructor"].includes(name))
      fail("invalid MCP server name");
    object(value, `MCP server ${name}`);
    if (Object.keys(value).some((key) => !["command", "url", "enabled"].includes(key)))
      fail(`nonportable MCP fields: ${name}`);
    if (value.enabled !== undefined && typeof value.enabled !== "boolean")
      fail(`invalid MCP enabled field: ${name}`);
    if (Boolean(value.command) === Boolean(value.url))
      fail(`MCP server needs command or url: ${name}`);
    if (value.command) {
      if (
        !Array.isArray(value.command) ||
        !value.command.length ||
        value.command.some((part) => typeof part !== "string" || !part || /[\r\n\0]/.test(part))
      )
        fail(`invalid MCP command: ${name}`);
      native[name] = { command: value.command[0], args: value.command.slice(1) };
      open[name] = { type: "local", command: value.command };
    } else {
      let url;
      try {
        url = new URL(value.url);
      } catch {
        fail(`invalid MCP URL: ${name}`);
      }
      if (
        !["https:", "http:"].includes(url.protocol) ||
        url.username ||
        url.password ||
        url.search ||
        url.hash
      )
        fail(`MCP URL must not contain credentials, query or fragment: ${name}`);
      native[name] = { type: "http", url: value.url };
      open[name] = { type: "remote", url: value.url };
    }
    if (value.enabled === false) open[name].enabled = false;
  }
  // Preserve unrelated project settings in their original provider only.
  const previousServers = state.servers ?? [];
  if (!Array.isArray(previousServers) || previousServers.some((name) => typeof name !== "string"))
    fail(`invalid servers receipt: ${statePath}`);
  const previousMcpEntries = object(state.mcpEntries ?? {}, `${statePath} mcpEntries`);
  for (const [provider, entries] of Object.entries(previousMcpEntries)) {
    object(entries, `${statePath} mcpEntries ${provider}`);
    for (const checksum of Object.values(entries))
      if (typeof checksum !== "string" || !/^[a-f0-9]{64}$/.test(checksum))
        fail(`invalid MCP entry receipt: ${statePath}`);
  }
  const mcpEntries = {};
  const managedNames = new Set([...previousServers, ...Object.keys(servers)]);
  function reconcileMcpEntries(name, entries, desired) {
    const previous = previousMcpEntries[name] ?? {};
    mcpEntries[name] = {};
    for (const key of managedNames) {
      const hasCurrent = Object.hasOwn(entries, key);
      const hasDesired = Object.hasOwn(desired, key);
      if (hasCurrent && !hasDesired) {
        if (!previous[key] || entryDigest(entries[key]) !== previous[key])
          fail(
            `managed MCP entry conflict in ${name}: ${key}; preserve the provider-specific entry under a different name or reconcile the canonical source first`,
          );
        delete entries[key];
        continue;
      }
      if (
        hasCurrent &&
        hasDesired &&
        !sameEntry(entries[key], desired[key]) &&
        (!previous[key] || entryDigest(entries[key]) !== previous[key])
      )
        fail(
          `managed MCP entry conflict in ${name}: ${key}; preserve the provider-specific entry under a different name or reconcile the canonical source first`,
        );
      if (hasDesired) {
        entries[key] = desired[key];
        mcpEntries[name][key] = entryDigest(desired[key]);
      }
    }
  }
  const existingMcp = object(opencode.mcp?.servers ?? opencode.mcp ?? {}, "OpenCode MCP");
  opencode.mcp = { ...existingMcp };
  reconcileMcpEntries("opencode.json", opencode.mcp, open);
  opencode.$schema ??= "https://opencode.ai/config.json";
  if (opencode.instructions !== undefined && !Array.isArray(opencode.instructions))
    fail("OpenCode instructions must be an array");
  opencode.instructions = [
    ...new Set([
      ...(opencode.instructions ?? []).map((item) =>
        typeof item === "string" ? item.replaceAll(".opencode/rules", ".agents/rules") : item,
      ),
      ".agents/rules/*.md",
    ]),
  ];
  write("opencode.json", json(opencode));
  for (const name of [".cursor/mcp.json", ".mcp.json"]) {
    const config = parse(name, {});
    config.mcpServers = { ...object(config.mcpServers ?? {}, name) };
    // Disabled servers are omitted because these providers lack a common flag.
    const desired = {};
    for (const [key, value] of Object.entries(native))
      if (servers[key].enabled !== false) desired[key] = value;
    reconcileMcpEntries(name, config.mcpServers, desired);
    write(name, json(config));
  }
  for (const name of [".codex/config.toml", ".grok/config.toml"]) {
    let text = read(name)?.toString() ?? "";
    const start = `# ${marker}:start`,
      end = `# ${marker}:end`;
    const existingBlock =
      text.indexOf(start) >= 0
        ? text.slice(text.indexOf(start), text.indexOf(end) + end.length)
        : "";
    const unmanaged = text.replace(existingBlock, "");
    // TOML stays lossless outside the block. Do not guess how to merge a table.
    for (const key of managedNames) {
      const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const quoted = `(?:${escaped}|["']${escaped}["'])`;
      const header = `(?:mcp_servers|["']mcp_servers["'])`;
      if (
        new RegExp(`^\\s*\\[\\s*${header}\\s*\\.\\s*${quoted}\\s*(?:\\.|\\])`, "m").test(
          unmanaged,
        ) ||
        new RegExp(`^\\s*${header}\\s*\\.\\s*${quoted}\\s*(?:\\.|\\s*=)`, "m").test(unmanaged)
      )
        fail(
          `unmanaged MCP table conflict in ${name}: ${key}; move its portable definition to .agents/mcp.json first`,
        );
    }
    const lines = [start];
    for (const [key, value] of Object.entries(native)) {
      if (servers[key].enabled === false) continue;
      lines.push("", `[mcp_servers.${JSON.stringify(key)}]`);
      if (value.command)
        lines.push(
          `command = ${JSON.stringify(value.command)}`,
          `args = ${JSON.stringify(value.args)}`,
        );
      else lines.push(`url = ${JSON.stringify(value.url)}`);
    }
    if (name.startsWith(".codex") && read(reviewer)) {
      if (/^\s*\[\s*agents\s*\.\s*["']?adversary["']?\s*\]/m.test(unmanaged))
        fail("unmanaged Codex adversary table conflict");
      lines.push(
        "",
        "[agents.adversary]",
        'description = "Adversarial reviewer for plans, docs, and diffs."',
        'config_file = "agents/adversary.toml"',
      );
    }
    lines.push("", end);
    write(name, scopedBlock(text, lines.join("\n"), "# ", ""));
  }
  // Remove only unchanged generated outputs whose canonical source was removed.
  for (const [name, checksum] of Object.entries(state.generated)) {
    if (generated[name] || preservedClaude.includes(name)) continue;
    const bytes = read(name);
    if (bytes && digest(bytes) !== checksum) fail(`edited generated file: ${name}`);
    if (bytes) removals.add(name);
  }
  write(
    statePath,
    json({
      schemaVersion: 1,
      generated,
      servers: Object.keys(servers).sort(),
      mcpEntries,
      preservedClaude,
    }),
  );
  const changes = [...writes]
    .filter(([name, bytes]) => !original.get(name)?.equals(bytes))
    .map(([name]) => name);
  for (const [name, mode] of modes)
    if (!fs.existsSync(location(name)) || (fs.statSync(location(name)).mode & 0o777) !== mode)
      changes.push(name);
  changes.push(...removals);
  if (!check) {
    // Detect a concurrent edit rather than replacing a file after reading it.
    for (const [name, bytes] of original) {
      const file = location(name);
      const current = fs.existsSync(file) ? fs.readFileSync(file) : null;
      if (bytes ? !current?.equals(bytes) : current !== null)
        fail(`file changed during sync: ${name}`);
    }
    for (const [name, bytes] of writes) {
      if (name === statePath) continue;
      if (!original.get(name)?.equals(bytes)) {
        fs.mkdirSync(path.dirname(location(name)), { recursive: true });
        fs.writeFileSync(location(name), bytes);
      }
      if (modes.has(name)) fs.chmodSync(location(name), modes.get(name));
    }
    for (const name of removals) fs.unlinkSync(location(name));
    // Publish ownership last. A failed removal must remain discoverable on retry.
    if (!original.get(statePath)?.equals(writes.get(statePath))) {
      fs.mkdirSync(path.dirname(location(statePath)), { recursive: true });
      fs.writeFileSync(location(statePath), writes.get(statePath));
    }
  }
  return { changes: [...new Set(changes)].sort() };
}

if (
  process.argv[1] &&
  fs.existsSync(process.argv[1]) &&
  fs.realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    const args = process.argv.slice(2);
    let root = process.cwd(),
      check = false;
    let preserveClaude;
    while (args.length) {
      const option = args.shift();
      if (option === "--check") check = true;
      else if (option === "--root" && args[0] && !args[0].startsWith("--")) root = args.shift();
      else if (option === "--preserve-claude" && args[0] && !args[0].startsWith("--")) {
        preserveClaude ??= [];
        preserveClaude.push(args.shift());
      } else
        fail(
          "usage: node scripts/provider-sync.mjs [--root PATH] [--check] [--preserve-claude PATH]",
        );
    }
    const result = syncProviders({ root, check, preserveClaude });
    if (result.changes.length)
      console.log(`${check ? "provider drift" : "provider sync"}:\n${result.changes.join("\n")}`);
    else console.log("provider sync: current");
    if (check && result.changes.length) process.exitCode = 1;
  } catch (error) {
    console.error(`provider sync: ${error.message}`);
    process.exitCode = 1;
  }
}
